WebApplication2/Models/VacantDeparture.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace WebApplication2.Models;

public class VacantDeparture
{
    [Key]
    public int vdID { get; set; }
    public int PID { get; set; }
    public string vacanDepartureName { get; set; }
    public string departureP { get; set; }
    public string departureCoord { get; set; }
    public string departureAdress { get; set; }
    public string arrivalP { get; set; }
    public DateTime departureD { get; set; }
    public DateTime arrivalD { get; set; }
    public int price { get; set; }
    public int seatsCount { get; set; }
    public int carriageCount { get; set; }


    [ValidateNever]
    public Train Train { get; set; } // from Train

    [ValidateNever]
    public IdentityUser provider { get; set; } //same as user from identity

    [ValidateNever]
    public ICollection<Ticket> Tickets { get; set; }
}

WebApplication2/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TicketController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Ticket
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                  .OrderByDescending(t => t.PurchaseDate)
                                  .ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            else
            {
                var id = _userManager.GetUserId(User);
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                .Include( t => t.user)
                                .Where(t => t.user.Id == id)
                                .OrderByDescending(t => t.PurchaseDate)
                                .ToListAsync()
                          ) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }

        }

        // GET: Ticket/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // GET: Ticket/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticketModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        // GET: Ticket/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel == null)
            {
                return NotFound();
            }
            return View(ticketModel);
        }

        // POST: Ticket/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (id != ticketModel.ticketID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticketModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticketModel.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        public async Task<IActionResult> Cancel(int id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticket = _context.TicketModels.FirstOrDefault(t => t.ticketID == id);

            ticket.status = "cancelled";
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticket.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }
        // GET: Ticket/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // POST: Ticket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TicketModels == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel != null)
            {
                _context.TicketModels.Remove(ticketModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketModelExists(int id)
        {
          return (_context.TicketModels?.Any(e => e.ticketID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Controllers/VacantDeparturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Infrastructure.Services;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class VacantDeparturesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IVacantDepartureService _vds;
        private readonly ITrainService _trainService;

        public VacantDeparturesController(
            ApplicationDbContext context, 
            UserManager<IdentityUser> userManager,
            IVacantDepartureService vds,
            ITrainService trainService)
        {
            _context = context;
            _userManager = userManager;
            _vds = vds;
            _trainService = trainService;
        }

        // GET: VacantDepartures
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var vacantDepatures = await _vds.GetVacantDepartures();
                return View(vacantDepatures);
            }
            else
            {
                var vacantDepatures = await _vds.GetVacantDepartures(_userManager.GetUserId(User));
                return View(vacantDepatures);
            }
        }

        // GET: VacantDepartures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VacantDepartures == null)
            {
                return NotFound();
            }

            var vacantDeparture = _vds.GetVacantDepartureDetails(id);

            if (vacantDeparture == null)
            {
                return NotFound();
            }

            vacantDeparture.Train = _trainService.GetTrainById(vacantDeparture.Train.trainTypeID);
            
            return View(vacantDeparture);
        }

        // GET: VacantDepartures/Create
        public IActionResult Create()
        {
            List<Train> trainTypes = _trainService.GetTrains();
            ViewBag.TrainTypes = new SelectList(trainTypes, "trainTypeID", "typeName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VacantDeparture vacantDeparture)
        {
            vacantDeparture.Train = _trainService.GetTrainById(vacantDeparture.Train.trainTypeID);
            vacantDeparture.seatsCount = _vds.CalculateTotalSeatsInDeparture(vacantDeparture.carriageCount, vacantDeparture.Train.trainSeats);
            var userId = _userManager.GetUserId(User);
            await _vds.CreateAsync(vacantDeparture, userId);
            return RedirectToAction(nameof(Index));
        }

        // GET: VacantDepartures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VacantDepartures == null)
            {
                return NotFound();
            }
            var vacantDeparture = await _context.VacantDepartures.FindAsync(id);
            if (vacantDeparture == null)
            {
                return NotFound();
            }
            return View(vacantDeparture);
        }

        // POST: VacantDepartures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VacantDeparture vacantDeparture)
        {
            if (id != vacantDeparture.vdID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _vds.EditAsync(vacantDeparture);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VacantDepartureExists(vacantDeparture.vdID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vacantDeparture);
        }

        // GET: VacantDepartures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VacantDepartures == null)
            {
                return NotFound();
            }

            var vacantDeparture = await _context.VacantDepartures
                .FirstOrDefaultAsync(m => m.vdID == id);
            if (vacantDeparture == null)
            {
                return NotFound();
            }

            return View(vacantDeparture);
        }

        // POST: VacantDepartures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _vds.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private bool VacantDepartureExists(int id)
        {
          return (_context.VacantDepartures?.Any(e => e.vdID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Views/VacantDepartures/Create.cshtml
@model WebApplication2.Models.VacantDeparture

@{
    ViewData["Title"] = "Create";
}


<div class="row con">
    <h1><a class="back" onclick="history.back();">←</a> Створення нового рейсу</h1>
    <br />
    <hr />
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Номер відправлення</label>
                <input asp-for="PID" class="form-control" />
                <span asp-validation-for="PID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Назва відправлення</label>
                <input asp-for="vacanDepartureName" class="form-control" />
                <span asp-validation-for="vacanDepartureName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Місце відправлення</label>
                <input asp-for="departureP" class="form-control" />
                <span asp-validation-for="departureP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Координати місця відправлення</label>
                <input asp-for="departureCoord" class="form-control" />
                <span asp-validation-for="departureCoord" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Адреса відправлення</label>
                <input asp-for="departureAdress" class="form-control" />
                <span asp-validation-for="departureAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Місце прибуття</label>
                <input asp-for="arrivalP" class="form-control" />
                <span asp-validation-for="arrivalP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата відправлення</label>
                <input asp-for="departureD" class="form-control" />
                <span asp-validation-for="departureD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Дата прибуття</label>
                <input asp-for="arrivalD" class="form-control" />
                <span asp-validation-for="arrivalD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ціна квитка</label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Модель вагона</label>
                <select asp-for="Train.trainTypeID" asp-items="@(ViewBag.TrainTypes)" class="form-control"></select>
                <span asp-validation-for="Train.trainTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Кількість вагонів</label>
                <input asp-for="carriageCount" class="form-control" />
                <span asp-validation-for="carriageCount" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
    @Html.HiddenFor(model => model.PID)
    @Html.HiddenFor(model => model.vacanDepartureName)
    @Html.HiddenFor(model => model.departureP)
    @Html.HiddenFor(model => model.departureCoord)
    @Html.HiddenFor(model => model.arrivalP)
    @Html.HiddenFor(model => model.departureD)
    @Html.HiddenFor(model => model.arrivalD)
    @Html.HiddenFor(model => model.price)
    @Html.HiddenFor(model => model.Train.trainTypeID)
    @Html.HiddenFor(model => model.carriageCount)
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
    .con {
        padding: 30px;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    }
            
    .back {
        font: 14pt;
        color: red;
        cursor: pointer;
        text-decoration: none;
    }
            
</style>

WebApplication2/Views/VacantDepartures/Delete.cshtml
@model WebApplication2.Models.VacantDeparture

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VacantDeparture</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vacanDepartureName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vacanDepartureName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departureP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departureCoord)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureCoord)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departureD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seatsCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seatsCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="vdID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/VacantDepartures/Details.cshtml
@model WebApplication2.Models.VacantDeparture

@{
    ViewData["Title"] = "Ordering";
}


<div class="con">
    <h1><a class="back" onclick="history.back();">←</a> @Model.vacanDepartureName (№ @Model.PID)</h1>
    <br />
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <label class="control-label">Номер відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PID)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Назва відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vacanDepartureName)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Місце відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureP)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Координати місця відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureCoord)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Місце прибуття</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalP)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Дата відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureD)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Дата прибуття</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalD)
        </dd>
        <dt class = "col-sm-2">
            <label class="control-label">Ціна квитка</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seatsCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seatsCount)
        </dd>
        <dt class="col-sm-2">
            <label class="control-label">Кількість вагонів</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.carriageCount)
        </dd>
        <dt class="col-sm-2">
            <label class="control-label">ID перевізника із таблиці Users</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.provider.Id)
        </dd>
        <dt class="col-sm-2">
            <label class="control-label">Модель вагонів потягу</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Train.typeName)
        </dd>
    </dl>

    <div>
        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.vdID">Змінити</a>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model?.vdID">Видалити</a>
    </div>
</div>

<style>
    .con {
        padding: 30px;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    }

    .back {
        font: 14pt;
        color: red;
        cursor: pointer;
        text-decoration: none;
    }
</style >

WebApplication2/Views/VacantDepartures/Index.cshtml
@model IEnumerable<WebApplication2.Models.VacantDeparture>

@{
    ViewData["Title"] = "Index";
    var currentPage = 1;
    int pageSize = 6;
    int totalPages = Math.Max(1, (int)Math.Ceiling((double)Model.Count() / pageSize));

    if (ViewContext.HttpContext.Request.Query.ContainsKey("page"))
    {
        currentPage = Convert.ToInt32(ViewContext.HttpContext.Request.Query["page"]);
    }
    currentPage = Math.Min(Math.Max(currentPage, 1), totalPages);
}

<h1>Рейси</h1>
<br>
<div class="row">
    <div class="col-md-3" @(User.IsInRole("Admin") ? "" : "hidden")>
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="UserEditor" asp-action="AdminDashboard">Головна</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" asp-area="" asp-controller="VacantDepartures" asp-action="">Рейси</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Trains" asp-action="">Типи потягів</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Ticket" asp-action="">Квитки</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="">Користувачі</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="Roles">Ролі</a>
            </li>
        </ul>
    </div>
    <div class="col-md-3" @(User.IsInRole("Admin") ? "hidden" : "")>
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="Dashboard">Статистика</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" asp-area="" asp-controller="VacantDepartures" asp-action="">Віші Рейси</a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link">Вийти</button>
                </form>
            </li>
        </ul>  
    </div>
    <div class="col-md-9">
        <p>
            <a asp-action="Create">Створити новий</a>
        </p>
        <table class="table">
            <thead class="dark">
                <tr>
                    <th>
                        <label>№</label>
                    </th>
                    <th>
                        <label>Назва відправлення</label>
                    </th>
                    <th>
                        <label>Місце відпрвлення</label>
                    </th>
                    <th>
                        <label>Місце прибуття</label>
                    </th>
                    <th>
                        <label>Дата відправлення</label>
                    </th>
                    <th>
                        <label>Дата прибуття</label>
                    </th>
                    <th>
                        <label>Ціна</label>
                    </th>
                    <th>
                        <label>Кількість вагонів</label>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                 @if (Model.Any())
                {
                    var pagedData = Model.Skip((currentPage - 1) * pageSize).Take(pageSize);
                    foreach (var item in pagedData)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.PID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.vacanDepartureName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.departureP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.arrivalP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.departureD)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.arrivalD)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.carriageCount)
                            </td>
                            <td>
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.vdID">Details</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <nav>
            <ul class="pagination justify-content-center">
                @if (currentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="?page=@(currentPage - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }


                @for (int i = 1; i <= totalPages; i++)
                {
                    <li class="page-item @(currentPage == i ? "active" : "")">
                        <a class="page-link" href="?page=@i">@i</a>
                    </li>
                }

                @if (currentPage < totalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="?page=@(currentPage + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

<style>
    .dark {
        color: white;
        background-color: black;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    } 
    td,th{
        vertical-align: middle;
    }
</style>