WebApplication2/Controllers/SearchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplication2.Data;
using WebApplication2.Models;
using ceTe.DynamicPDF;
using ceTe.DynamicPDF.PageElements;
using ceTe.DynamicPDF.PageElements.BarCoding;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Net.Mime;
using NuGet.Packaging;
using WebApplication2.Infrastructure.Interfaces;
using System.IO;

namespace WebApplication2.Controllers
{
    public class SearchController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ISendGridApiService _sendGridApiService;
        private const double EarthRadiusKm = 6371;

        public SearchController(ApplicationDbContext context, UserManager<IdentityUser> userManager, ISendGridApiService sendGridApiService)
        {
            _context = context;
            _userManager = userManager;
            _sendGridApiService = sendGridApiService;
        }


        // GET: SearchController
        public ActionResult Index()
        {
            //SendEmail();
            return View();
        }

        public ActionResult Search(Search? model, string? lat, string? lon, string? nearestModel)
        {
            model.searchTime = DateTime.Now;

            /*lat = "50,438607"; // test data for geo
            *lon = "30,486810";
            */

            List<VacantDeparture> results;
            if (nearestModel == null)
            {
                results = _context.VacantDepartures
                .Where(departure =>
                    departure.departureP.Contains(model.departurePoint) &&
                    departure.arrivalP.Contains(model.destinationPoint) &&
                    departure.departureD > model.searchTime.AddMinutes(5) &&
                    departure.departureD < model.departureDate.AddDays(7))
                .OrderBy(departure => departure.departureD)
                .ToList();
            }
            else
            {
                var newModel = JsonConvert.DeserializeObject<Search>(nearestModel);
                results = _context.VacantDepartures
               .Where(departure =>
                   departure.departureP.Contains(newModel.departurePoint) &&
                   departure.arrivalP.Contains(newModel.destinationPoint) &&
                   departure.departureD > newModel.searchTime.AddMinutes(10) &&
                   departure.departureD > newModel.departureDate)
               .OrderBy(departure => departure.departureD)
               .ToList();
            }

            var filteredResults = new List<VacantDeparture>();

            foreach (var result in results)
            {
                var SoldTicketCount = _context.TicketModels.Count(ticket => ticket.vacantDepatureID == result.vdID && ticket.status == "sold");
                if (result.seatsCount - SoldTicketCount > 0)
                {
                    string[] coords = result.departureCoord.Split(' ');

                    if (result.departureD > model.searchTime.AddMinutes(10))
                    {
                        filteredResults.Add(result);
                    }
                    else if (result.departureD < model.searchTime.AddMinutes(10) && CalculateDistance(lat, lon, coords[0], coords[1]) < 100)
                    {
                        filteredResults.Add(result);
                    }

                }
            }

            TempData["SearchModel"] = JsonConvert.SerializeObject(model);
            ViewBag.SearchModel = model;
            return View(filteredResults);
        }

        public ActionResult SecondTicketSearch(string selectedCarriage, string selectedSeat, int depID, DateTime returnDate)
        {
            var depModel = _context.VacantDepartures.FirstOrDefault(dearture => dearture.vdID == depID);

            Search searchModel = new Search();
            searchModel.searchTime = DateTime.Now;
            searchModel.departurePoint = depModel.arrivalP;
            searchModel.destinationPoint = depModel.departureP;
            searchModel.departureDate = returnDate;

            var results = _context.VacantDepartures
            .Where(departure =>
                departure.departureP == searchModel.departurePoint &&
                departure.arrivalP == searchModel.destinationPoint &&
                departure.departureD > searchModel.searchTime.AddMinutes(10) &&
                departure.departureD > searchModel.departureDate)
            .OrderBy(departure => departure.departureD)
            .ToList();

            var filteredResults = new List<VacantDeparture>();

            foreach (var result in results)
            {
                var SoldTicketCount = _context.TicketModels.Count(ticket => ticket.vacantDepatureID == result.vdID && ticket.status == "sold");
                if (result.seatsCount - SoldTicketCount > 0)
                {
                    filteredResults.Add(result);
                }
            }

            ViewBag.MainVacDep = depID;
            ViewBag.MainChosenSeats = selectedSeat;
            ViewBag.MainChosenCars = selectedCarriage;

            return View(filteredResults);
        }

        public async Task<IActionResult> Ordering(int? id)
        {
            if (id == null || _context.VacantDepartures == null)
            {
                return NotFound();
            }

            var model = JsonConvert.DeserializeObject<Search>(TempData["SearchModel"].ToString());

            ViewBag.returnDate = model.returnDate;

            var vacantDeparture = await _context.VacantDepartures
                .Include(vd => vd.Train) // Include the Train navigation property
                .Include(vd => vd.provider) // Include the provider navigation property
                .FirstOrDefaultAsync(m => m.vdID == id);

            if (vacantDeparture == null)
            {
                return NotFound();
            }

            vacantDeparture.Train = _context.Trains.FirstOrDefault(train => train.trainTypeID == vacantDeparture.Train.trainTypeID);

            ViewBag.SeatsCount = vacantDeparture.Train.trainSeats;
            ViewBag.CarriageCount = vacantDeparture.carriageCount;
            if (vacantDeparture.Train.trainRows != 0)
            {
                ViewBag.Rows = vacantDeparture.Train.trainRows;
            }
            else
            {
                ViewBag.Rows = 2;
            }

            List<List<int>> occupiedSeats = new List<List<int>>();
            for (int i = 1; i <= vacantDeparture.carriageCount; i++)
            {
                occupiedSeats.Add(GetVacantSeats(vacantDeparture, i));
            }
            ViewBag.Seats = occupiedSeats;

            return View(vacantDeparture);
        }

        public async Task<IActionResult> OrderingSecondTicket(int? returnId, int mainVacDepId, string mainChosenSeats, string mainChosenCars)
        {
            if (returnId == null || _context.VacantDepartures == null)
            {
                return NotFound();
            }

            var vacantDeparture = await _context.VacantDepartures
                .Include(vd => vd.Train) // Include the Train navigation property
                .Include(vd => vd.provider) // Include the provider navigation property
                .FirstOrDefaultAsync(m => m.vdID == returnId);

            if (vacantDeparture == null)
            {
                return NotFound();
            }

            vacantDeparture.Train = _context.Trains.FirstOrDefault(train => train.trainTypeID == vacantDeparture.Train.trainTypeID);

            ViewBag.SeatsCount = vacantDeparture.Train.trainSeats;
            ViewBag.CarriageCount = vacantDeparture.carriageCount;

            if (vacantDeparture.Train.trainRows != 0)
            {
                ViewBag.Rows = vacantDeparture.Train.trainRows;
            }
            else
            {
                ViewBag.Rows = 2;
            }

            ViewBag.mainVacDepId = mainVacDepId;
            ViewBag.mainChosenSeats = mainChosenSeats;
            ViewBag.mainChosenCars = mainChosenCars;

            List<List<int>> occupiedSeats = new List<List<int>>();
            for (int i = 1; i <= vacantDeparture.carriageCount; i++)
            {
                occupiedSeats.Add(GetVacantSeats(vacantDeparture, i));
            }
            ViewBag.Seats = occupiedSeats;

            return View(vacantDeparture);

        }

        public ActionResult SummingUp(int id, string SelectedCarriage, string SelectedSeat, int? mainVacDepId, string? mainChosenSeats, string? mainChosenCars)
        {
            var returnDep = _context.VacantDepartures.FirstOrDefault(departure => departure.vdID == id);


            if (returnDep == null)
            {
                return NotFound();
            }

            var uid = _userManager.GetUserId(User);
            var currentUser = _context.Users.FirstOrDefault(u => u.Id == uid);
            if (currentUser == null)
            {
                ViewBag.isPhoneEmpty = false;
            }
            else
            {
                ViewBag.isPhoneEmpty = string.IsNullOrEmpty(currentUser.PhoneNumber);
            }

            List<TicketModel> tickets = new List<TicketModel>();

            var returnSepSeats = SelectedSeat.Split(',');
            var returnSepCars = SelectedCarriage.Split(',');
            double sum = 0;

            if (mainVacDepId != null)
            {
                var mainVacDep = _context.VacantDepartures.FirstOrDefault(departure => departure.vdID == mainVacDepId);

                if (mainVacDep == null)
                {
                    return NotFound();
                }

                var mainSepSeats = mainChosenSeats.Split(',');
                var mainSepCars = mainChosenCars.Split(',');

WebApplication2/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TicketController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Ticket
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                  .OrderByDescending(t => t.PurchaseDate)
                                  .ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            else
            {
                var id = _userManager.GetUserId(User);
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                .Include( t => t.user)
                                .Where(t => t.user.Id == id)
                                .OrderByDescending(t => t.PurchaseDate)
                                .ToListAsync()
                          ) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }

        }

        // GET: Ticket/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // GET: Ticket/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticketModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        // GET: Ticket/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel == null)
            {
                return NotFound();
            }
            return View(ticketModel);
        }

        // POST: Ticket/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (id != ticketModel.ticketID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticketModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticketModel.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        public async Task<IActionResult> Cancel(int id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticket = _context.TicketModels.FirstOrDefault(t => t.ticketID == id);

            ticket.status = "cancelled";
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticket.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }
        // GET: Ticket/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // POST: Ticket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TicketModels == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel != null)
            {
                _context.TicketModels.Remove(ticketModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketModelExists(int id)
        {
          return (_context.TicketModels?.Any(e => e.ticketID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
    @using Microsoft.AspNetCore.Identity
    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" @(User.IsInRole("Admin") || User.IsInRole("Provider") ? "hidden": "")>
                    <img src="~/images/train-logo.png" alt="logo.svg" width="auto" height="24">
                </a>
                <a class="navbar-brand" @(User.IsInRole("Admin") ? "": "hidden")>
                    <img src="~/images/train-adashboard-logo.png" alt="logo.svg" width="auto" height="24">
                </a>
                <a class="navbar-brand" @(User.IsInRole("Provider") ? "": "hidden")>
                    <img src="~/images/train-dashboard-logo.png"  alt="logo.svg" width="auto" height="24">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" @(User.IsInRole("Admin")? "hidden": "")>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">
                                Головна
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                Про нас
                            </a>
                        </li>
                        <li class="nav-item" @(User.Identity.IsAuthenticated && !User.IsInRole("Admin") && !User.IsInRole("Provider") ? "": "hidden")>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="">Квитки</a>
                        </li>
                        @{
                            var controller = ViewContext?.RouteData?.Values?["Controller"]?.ToString();
                            var action = ViewContext?.RouteData?.Values?["Action"]?.ToString();
                        }
                        <li class="nav-item" @(User.IsInRole("Admin") ? "" : "hidden")>
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="@(controller != "UserEditor" && action != "AdminDashboard" ? "UserEditor" : "Search")" 
                                asp-action="@(controller != "UserEditor" && action != "AdminDashboard" ? "AdminDashboard" : "Index")"
                            >
                                До @(controller == "UserEditor" && action == "AdminDashboard" ? "сайту" : "адміністративної панелі")
                            </a>
                        </li>
                        <li class="nav-item" @(User.IsInRole("Provider") ? "" : "hidden")>
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="@(controller != "UserEditor" && action != "Dashboard" ? "UserEditor" : "Search")" 
                                asp-action="@(controller != "UserEditor" && action != "Dashboard" ? "Dashboard" : "Index")"
                            >
                                До @(controller == "UserEditor" && action == "Dashboard" ? "сайту" : "панелі")
                            </a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TicketPoint - <a asp-area="" asp-controller="Home" asp-action="Privacy">Про нас</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>