WebApplication2/Models/Ticket.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace WebApplication2.Models;

public class Ticket
{
    [Key]
    public int ticketID { get; set; }
    public int ticketPID { get; set; }
    public string departureP { get; set; }
    public string arrivalP { get; set; }
    public DateTime departureD { get; set; }
    public DateTime arrivalD { get; set; }
    public string passengerFullName { get; set; }
    public int carriageNumber { get; set; }
    public int seat { get; set; }
    public string status { get; set; }

    [ValidateNever]
    public VacantDeparture vacDep { get; set; } //from Vacant Departure

    [ValidateNever]
    public IdentityUser user { get; set; } //user from identity
}

WebApplication2/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TicketController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TicketController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Ticket
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                  .OrderByDescending(t => t.PurchaseDate)
                                  .ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            else
            {
                var id = _userManager.GetUserId(User);
                return _context.TicketModels != null ?
                          View(
                              await _context.TicketModels
                                .Include( t => t.user)
                                .Where(t => t.user.Id == id)
                                .OrderByDescending(t => t.PurchaseDate)
                                .ToListAsync()
                          ) :
                          Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }

        }

        // GET: Ticket/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // GET: Ticket/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ticketModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        // GET: Ticket/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel == null)
            {
                return NotFound();
            }
            return View(ticketModel);
        }

        // POST: Ticket/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ticketID,ticketPID,departureP,arrivalP,departureD,arrivalD,passengerFullName,carriageNumber,seat,status,vacantDepatureID")] TicketModel ticketModel)
        {
            if (id != ticketModel.ticketID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticketModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticketModel.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticketModel);
        }

        public async Task<IActionResult> Cancel(int id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticket = _context.TicketModels.FirstOrDefault(t => t.ticketID == id);

            ticket.status = "cancelled";
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketModelExists(ticket.ticketID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }
        // GET: Ticket/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TicketModels == null)
            {
                return NotFound();
            }

            var ticketModel = await _context.TicketModels
                .FirstOrDefaultAsync(m => m.ticketID == id);
            if (ticketModel == null)
            {
                return NotFound();
            }

            return View(ticketModel);
        }

        // POST: Ticket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TicketModels == null)
            {
                return Problem("Entity set 'ApplicationDbContext.TicketModels'  is null.");
            }
            var ticketModel = await _context.TicketModels.FindAsync(id);
            if (ticketModel != null)
            {
                _context.TicketModels.Remove(ticketModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketModelExists(int id)
        {
          return (_context.TicketModels?.Any(e => e.ticketID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Controllers/TrainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Infrastructure.Services;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TrainsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFileService _fileService;
        private readonly ITrainService _trainService;

        public TrainsController(ApplicationDbContext context,
            IFileService fileService,
            ITrainService trainService)
        {
            _context = context;
            _fileService = fileService;
            _trainService = trainService;
        }

        // GET: Trains
        public async Task<IActionResult> Index()
        {
            var trains = await _trainService.GetTrainsAsync();
            return View(trains);
        }

        // GET: Trains/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var train = await _context.Trains
                .FirstOrDefaultAsync(m => m.trainTypeID == id);

            if (train == null)
            {
                return NotFound();
            }

            return View(train);
        }

        // GET: Trains/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trains/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTrainModelIn trainModel,
            IFormFile schema)
        {
            var schemaPath = await _fileService.SaveFileAsync(schema);

            if (ModelState.IsValid)
            {
                await _trainService.CreateAsync(trainModel, schemaPath!);
                return RedirectToAction(nameof(Index));
            }

            return View(trainModel);
        }

        // GET: Trains/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trains == null)
            {
                return NotFound();
            }

            var train = await _context.Trains.FindAsync(id);
            if (train == null)
            {
                return NotFound();
            }
            return View(train);
        }

        // POST: Trains/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("trainTypeID,typeName,trainSeats")] Train train)
        {
            if (id != train.trainTypeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(train);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainExists(train.trainTypeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(train);
        }

        // GET: Trains/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trains == null)
            {
                return NotFound();
            }

            var train = await _context.Trains
                .FirstOrDefaultAsync(m => m.trainTypeID == id);
            if (train == null)
            {
                return NotFound();
            }

            return View(train);
        }

        // POST: Trains/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trains == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Trains'  is null.");
            }
            var train = await _context.Trains.FindAsync(id);
            if (train != null)
            {
                _context.Trains.Remove(train);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainExists(int id)
        {
            return (_context.Trains?.Any(e => e.trainTypeID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Views/Ticket/Create.cshtml
@model WebApplication2.Models.TicketModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TicketModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ticketPID" class="control-label"></label>
                <input asp-for="ticketPID" class="form-control" />
                <span asp-validation-for="ticketPID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departureP" class="control-label"></label>
                <input asp-for="departureP" class="form-control" />
                <span asp-validation-for="departureP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrivalP" class="control-label"></label>
                <input asp-for="arrivalP" class="form-control" />
                <span asp-validation-for="arrivalP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="departureD" class="control-label"></label>
                <input asp-for="departureD" class="form-control" />
                <span asp-validation-for="departureD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="arrivalD" class="control-label"></label>
                <input asp-for="arrivalD" class="form-control" />
                <span asp-validation-for="arrivalD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="passengerFullName" class="control-label"></label>
                <input asp-for="passengerFullName" class="form-control" />
                <span asp-validation-for="passengerFullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="carriageNumber" class="control-label"></label>
                <input asp-for="carriageNumber" class="form-control" />
                <span asp-validation-for="carriageNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="seat" class="control-label"></label>
                <input asp-for="seat" class="form-control" />
                <span asp-validation-for="seat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vacantDepatureID" class="control-label"></label>
                <input asp-for="vacantDepatureID" class="form-control" />
                <span asp-validation-for="vacantDepatureID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Ticket/Delete.cshtml
@model WebApplication2.Models.TicketModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TicketModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ticketPID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ticketPID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departureP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departureD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.arrivalD)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalD)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.passengerFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.passengerFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.carriageNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.carriageNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.vacantDepatureID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vacantDepatureID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ticketID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/Ticket/Details.cshtml
@model WebApplication2.Models.TicketModel

@{
    ViewData["Title"] = "Details";
}

<div class="con">
    <h1><a onclick="history.back();" class="back">←</a> Квиток № @Model.ticketPID 
        <span class=@(Model.status == "sold" ? "s" : "c")>
            @Html.DisplayFor(model => model.status)
        </span>
    </h1>
    <br />
    <h4>Деталі</h4>
    <hr />
    <dl class="row">

        <dt class = "col-sm-2">
            <label>Місце відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureP)
        </dd>
        <dt class = "col-sm-2">
            <label>Місце прибуття</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalP)
        </dd>
        <dt class = "col-sm-2">
             <label>Дата відправлення</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departureD)
        </dd>
        <dt class = "col-sm-2">
            <label>Дата прибуття</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.arrivalD)
        </dd>
        <dt class = "col-sm-2">
             <label>Прізвище та Ім'я пасажира</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.passengerFullName)
        </dd>
        <dt class = "col-sm-2">
            <label>Номер вагону</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.carriageNumber)
        </dd>
        <dt class = "col-sm-2">
            <label>Номер місця</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seat)
        </dd>
        <dt class="col-sm-2">
            <label>Дата бронювання</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>
        <dt class="col-sm-2">
            <label>Тип квитка</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ticketAgeType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.addtionalOptions)
        </dt>
        <dd class="col-sm-10">
             <label>Додаткові послуги</label>
        </dd>
        <dt class="col-sm-2" @(User.IsInRole("Admin") ? "":"hidden")>
             <label>Номер рейсу у таблиці VacantDepartures</label>
        </dt>
        <dd class="col-sm-10" @(User.IsInRole("Admin") ? "":"hidden")>
            @Html.DisplayFor(model => model.vacantDepatureID)
        </dd>
    </dl>

    <div>
        @if (User.IsInRole("Admin"))
        {
            <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.ticketID">Змінити</a>
            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model?.ticketID">Видалити</a>
        }
        @if(Model.status != "cancelled")
        {
            <a class="btn btn-outline-danger" asp-action="Cancel" asp-route-id="@Model?.ticketID">Скасувати</a>
        }
    </div>
</div>

<style>
    .con {
        padding: 30px;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    }
    .c {
        background-color:red;
        color:white;
        border-radius:5px;
        padding:5px;
    }
    .s{
        background-color: green;
        color: white;
        border-radius: 5px;
        padding: 5px;
    }

    .back {
        font: 14pt;
        color: red;
        cursor: pointer;
        text-decoration: none;
    }
</style>

WebApplication2/Views/Ticket/Index.cshtml
@model IEnumerable<WebApplication2.Models.TicketModel>

@{
    ViewData["Title"] = "Index";
    var currentPage = 1;
    int pageSize = 6;
    int totalPages = Math.Max(1, (int)Math.Ceiling((double)Model.Count() / pageSize));

    if (ViewContext.HttpContext.Request.Query.ContainsKey("page"))
    {
        currentPage = Convert.ToInt32(ViewContext.HttpContext.Request.Query["page"]);
    }
    currentPage = Math.Min(Math.Max(currentPage, 1), totalPages);
    
}

<h1>Квитки</h1>
<br>

<div class="row">
    <div class="col-md-3" @(User.IsInRole("Admin") ? "" : "hidden")>
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="AdminDashboard">Головна</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="VacantDepartures" asp-action="">Рейси</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Trains" asp-action="">Типи потягів</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" asp-area="" asp-controller="Ticket" asp-action="">Квитки</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="">Користувачі</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="UserEditor" asp-action="Roles">Ролі</a>
            </li>
        </ul>
    </div>
    <div class=@(User.IsInRole("Admin") ? "col-md-9" : "")>

        <table class="table">
            <thead class=@(User.IsInRole("Admin") ? "dark" : "tckt")>
                <tr>
                    <th>
                        <label>№</label>
                    </th>
                    <th>
                        <label>Відправлення</label>
                    </th>
                    <th>
                        <label>Дата відправлення</label>
                    </th>
                    <th>
                        <label>Дата прибуття</label>
                    </th>
                    <th>
                        <label>ПІ Пасажира</label>
                    </th>
                    <th @(User.IsInRole("Admin") ? "hidden" : "")>
                        <label>Вагон (№)</label>
                    </th>
                    <th @(User.IsInRole("Admin") ? "hidden" : "")>
                        <label>Місце (№)</label>
                    </th>
                    <th @(User.IsInRole("Admin") ? "" : "hidden")>
                        <label>Дата покупки</label>
                    </th>
                    <th>
                        <label>Статус</label>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    var pagedData = Model.Skip((currentPage - 1) * pageSize).Take(pageSize);
                    foreach (var item in pagedData)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ticketPID)
                            </td>
                            <td>
                                <label>@item.departureP - @item.arrivalP</label>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.departureD)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.arrivalD)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.passengerFullName)
                            </td>
                            <td @(User.IsInRole("Admin") ? "hidden" : "")>
                                @Html.DisplayFor(modelItem => item.carriageNumber)
                            </td>
                            <td @(User.IsInRole("Admin") ? "hidden" : "")>
                                @Html.DisplayFor(modelItem => item.seat)
                            </td>
                            <td @(User.IsInRole("Admin") ? "" : "hidden")>
                                @Html.DisplayFor(modelItem => item.PurchaseDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.status)
                            </td>
                            <td>
                                <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.ticketID">Деталі</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="10" style="text-align: center">Немає квитків для відображення</td>
                    </tr>
                }
            </tbody>
        </table>

        <nav>
            <ul class="pagination justify-content-center">
                @if (currentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="?page=@(currentPage - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }

                @for (int i = 1; i <= totalPages; i++)
                {
                    <li class="page-item @(currentPage == i ? "active" : "")">
                        <a class="page-link" href="?page=@i">@i</a>
                    </li>
                }

                @if (currentPage < totalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="?page=@(currentPage + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>
<style>
    .tckt {
        color: white;
        background-color: #1560BD;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    }

    .dark {
        color: white;
        background-color: black;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    }

    th,
    td {
        vertical-align: middle;
    }

    .table a {
        width: 100%;
    }
</style>